### PR TITLE
Update Control_Theory.md

### PR DESCRIPTION
**Pull request by dt1729**
Added an extra course should I add some more for advanced control introduction or drone-specific methods?

### CODE REVIEW

**Comment by adityashriwastava7** [comment]
Underactuated Robotics by Russ Tedrake is already there in "Robot Specific/Legged Robot"

**Comment by adityashriwastava7** [comment]
> Added an extra course should I add some more for advanced control introduction or drone-specific methods?

If you know some good drone-specific course then please add in "Robot Specific/Drone"

**Comment by adityashriwastava7** [comment]
If you find some alternative of Advanced Control system 1, than that will be great contribution as it is not open.

**Comment by dt1729** [comment]
I saw Berkeley's advanced control systems course it's more of optimisation + MDP + RL + Optimal control rather than control theory or control for robotics. Ik individual courses for the same but not one that has all. 

I know a drone course but it doesn't have videos just slides and project code.

Underactuated has a lot of control stuff that's relevant for robotics, I believe rather than obscuring it into legged robots we should mention it here as a Note.

**Comment by adityashriwastava7** [comment]
I have added CS287 for lectures 1 to 9, as it is a very good resource on LQR, iterative LQR, and MPC. And it also sets a great foundation for learning-based control.

**Comment by adityashriwastava7** [comment]
Moved Underactuated Robotics from Legged Robot to Control Theory.

**Comment by adityashriwastava7** [comment]
Add the drone course within "Robot Specific/Unmanned Aerial Vehicle".
Also, attach the link to slides and project code.

**Pull request closed without merging**
